planet:
  radius: 6051800.0
  gravity: 8.87
  rotation_period_days: 243.025
  retrograde: true
  obliquity_deg: 2.64
  orbital_period_days: 224.7
  solar_constant: 2600.0
  surface_pressure: 9200000.0
numerics:
  truncation: 42
  nlat: 64
  nlon: 128
  nlev: 60
  dt: 1200.0
  semi_implicit_alpha: 0.5
  hyperdiff_order: 4
  hyperdiff_tau_smallest: 3600.0
  dealiasing: true
  leapfrog_raw_coeff: 0.04
physics:
  solar_profile: uniform_50_80km
  newtonian_profile: crisp1989
  enable_solar: true
  enable_newtonian: true
  solar_peak_heating_K_per_day: 15.0
  kz: 0.15
  rayleigh_low_tau: 86400.0
  sponge_top_height: 80000.0
  sponge_tau: 43200.0
